version: "3.8"
services:
 postgres:
  image: postgres:15-alpine
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=users_db
  ports:
    - "5432:5432"
  healthcheck: 
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
 api:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "8080:8080"
   environment:
     - DB_SOURCE=postgresql://root:password@postgres:5432/users_db?sslmode=disable
   depends_on:
       postgres:
        condition: service_healthy
  
  
   
    






