version: "3.8"

services:

 postgres:
   container_name: postgres-db
   image: postgres:15-alpine
   environment:
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=users_db
   ports:
     - "5432:5432"
   networks:
     - code_studio_network
   healthcheck: 
     test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]

      
 api:
   container_name: go-auth-service-api
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "8080:8080"
   networks:
     - code_studio_network
   environment:
     - DB_SOURCE=postgresql://root:password@postgres:5432/users_db?sslmode=disable
   depends_on:
       postgres:
         condition: service_healthy

networks:
  code_studio_network:
  
  
   
    






