// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	GetListUsers(ctx context.Context, arg GetListUsersParams) ([]GetListUsersRow, error)
	// -- name: GetSession :one
	// SELECT * FROM sessions
	// WHERE id = $1 LIMIT 1;
	GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByNameOrEmail(ctx context.Context, arg GetUserByNameOrEmailParams) (User, error)
	GetVerifyEmail(ctx context.Context, id int64) (VerifyEmail, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
